name: node-version

on:
  pull_request:
    paths: .node-version

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: /.node-version
          sparse-checkout-cone-mode: false

      - name: Check a node version is available on node-build
        run: curl -fsIo /dev/null "https://raw.githubusercontent.com/nodenv/node-build/master/share/node-build/$(< .node-version)"
